SELECT C.*, CONCAT_WS(', ', 
    CASE WHEN C.id IN (SELECT P.id FROM PEMAIN P) THEN 'pemain' END,
    CASE WHEN C.id IN (SELECT S.id FROM SUTRADARA S) THEN 'sutradara' END,
    CASE WHEN C.id IN (SELECT PS.id FROM PENULIS_SKENARIO PS) THEN 'penulis_skenario' END
  ) AS tipe
FROM CONTRIBUTORS C;